#+OPTIONS: toc:nil ':t num:nil

#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [12pt]
#+LATEX_HEADER: \usepackage{geometry}
#+LaTeX_HEADER: \usepackage{lmodern}
#+LATEX_HEADER: \usepackage[francais]{babel}
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://culturenumerique.univ-lille3.fr/css/base.css" />


#+TITLE: La messagerie électronique et les cookies
#+AUTHOR: Culture numérique
#+DATE:

* Le cas des mails

Le mail est un autre exemple de système client/serveur et les
programmes qui nous servent à lire nos messages sont des clients
mail. Il en existe de nombreuses sortes mais leurs fonctionnalités
sont comparables. Parmi les options possibles, ils proposent tous de
choisir si les messages que l'on envoie et surtout ceux qu'on lit
s'affichent au format texte ou au format =html=.

En effet, lorsque cette application de messagerie a été inventée, bien
avant l'invention du web,  les mails ne pouvaient contenir que du
texte sans aucune mise en forme. Mais cette norme a évolué et il est
possible de modifier la présentation du texte de nos messages et même
d'y inclure des éléments de structure, d'y insérer des images ou
d'autres ressources exactement comme dans une page web.

Lors de la lecture d'un tel message, le client mail qui a en charge
l'affichage se comporte exactement comme un client web. Les
différentes ressources font l'objet de requêtes =http= telles que nous
les avons décrites précédemment.

Les remarques sur les cookies et les mouchards s'appliquent donc comme
pour le web. Très concrètement, la simple lecture d'un message au
format =html=, peut donc envoyer beaucoup d'informations à des serveurs
tiers du type : le mail a été lu, nous avons cliqué sur tel ou tel
lien, etc, autant de choses qui ne sont pas possibles si le message
n'est qu'un simple texte.  

Les boutons de réseaux sociaux ont également la même fonction que sur
les pages web. 

Par exemple, à la réception d'une newsletter envoyée en masse,
l'expéditeur peut savoir si nous avons lu le message ou pas, ce qui
dans le cas de liste de diffusion de plusieurs dizaines de milliers
d'adresses, permet de trier les adresses valides des adresses
abandonnées. Les listes d'adresses valides (quelqu'un la lit
régulièrement) se revendent très chères et sont entre autres à
l'origine de nombreux spams.

Vous pouvez paramétrer votre client mail pour lire les messages comme
si ils n'avaient pas été écrits en =html= mais comme un simple texte. Ou
vous pouvez lui indiquer de ne jamais réaliser de requête web : vous
ne verrez peut être pas les images et peut être que la mise en forme
ne sera pas agréable ou optimale. En contrepartie aucune requête ne
sera alors faite vers une ressource extérieure. Personne ne pourra
donc /pister/ vos actions. À vous de régler votre lecteur de mail
avec les paramètres qui correspondent à ce que voulez faire.

De la même manière, vous pouvez paramétrer votre client mail pour
envoyer des messages soit en texte seul soit au format =html=.

* Le cas des pièces jointes

Notons qu'une pièce jointe fait partie d'un message, il est envoyé
avec le corps du message et ne constitue pas une ressource externe. On
peut donc s'échanger des messages avec des images en pièce jointe sans
utiliser l'affichage =html=. 

