#!/bin/bash
if (git status | grep dev)
then

	git checkout -B gh-pages dev
	for i in module1 module2 module3
	do
		echo item: $i/$i.html
    		git add -f $i/$i.html
	done
	git commit -m 'updated html files'
	git checkout dev
fi
