#+OPTIONS:   toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t ':t
#+LANGUAGE: fr
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [12pt,a4paper]
#+LaTeX_CLASS_OPTIONS: [hidelinks]
#+LATEX_HEADER: \usepackage{geometry,lmodern,xcolor}
#+LATEX_HEADER: \usepackage[french]{babel}
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://culturenumerique.univ-lille3.fr/css/base.css" />
#+OPTIONS: inline:nil 

#+TITLE: Internet: historique, usages, société
#+AUTHOR: Culture Numérique

* Informatique et numérique
  :PROPERTIES:
  :video:    https://player.vimeo.com/video/122104210
  :END:
À l'origine, les ordinateurs étaient réservés aux informaticiens, ou plutôt comme cette discipline naissait à peine, aux mathématiciens et électroniciens qui les créaient. En anglais un ordinateur se nomme /computer/ , dont la traduction exacte est /calculateur/.

Fondamentalement les ordinateurs ne font que des calculs, ils ne savent pas manipuler autre chose que des nombres, qui plus est des nombres représentés sous forme binaire c'est-à-dire avec des 0 et des 1. En effet, comme toutes les machines électriques la seule information qu'ils /comprennent/ est de la forme, /y'a du courant/ ou /y'a pas de courant/.

Or, aujourd'hui, nous utilisons tous des ordinateurs tous les jours, non pas pour faire des calculs mais pour tout un tas d'activités diverses et variées qu'elles soient professionnelles, liées à nos loisirs ou à notre vie quotidienne. Et pourtant, ces ordinateurs ne sont toujours que des machines qui font des calculs. Il a donc fallu trouver des techniques pour traduire/coder le texte, le son, les images avec des nombres. C'est ce qu'on appelle la numérisation. On dit souvent que notre monde est analogique (ou continu) et que le monde des machines est numérique (ou digital). Les scanners, appareils photo numériques, enregistreurs mp3 par exemple sont des dispositifs qui permettent de passer du monde analogique des hommes au monde numérique des machines, c'est-à-dire de numériser les informations sous forme de nombres que les ordinateurs vont pouvoir manipuler.

Nous vivons dans un monde où le numérique a pris beaucoup de place :  internet, la radio, la télévision, la téléphonie, la photographie et bien d'autres choses que nous ne soupçonnons pas sont entièrement numériques et donc manipulables par des ordinateurs au sens large, par exemple, des tablettes, des smartphones, les box adsl … en fait toutes les machines qui fonctionnent avec des processeurs, (nous reviendrons sur ce terme).

Cela représente des enjeux de société très importants. le numérique a ouvert des possibilités gigantesques en terme de gain de temps, de facilité de traitement, de nouvelles fonctionnalités, d'accès aux informations, aux archives etc. mais en même temps de nouvelles questions sont apparues : où sont stockées les données, qui y a accès, sont-elles en sécurité, sommes-nous dépendants de machines, de logiciels, de sociétés commerciales.

Pour que ces questions ne restent pas dans les mains des informaticiens, il est nécessaire que chacun fasse l'effort de comprendre les bases, les fondements de ces technologies qui nous entourent. Le citoyen du XXIème siècle a besoin d'une véritable culture numérique qui ne se limite pas à l'utilisation de FaceBook ou d'un traitement de texte. C'est ce que nous allons développer dans ces cours...

* Historique informatique
  :PROPERTIES:
  :video:    https://player.vimeo.com/video/122104231
  :END:

Les premiers ordinateurs ont été conçus et réalisés vers la fin de la seconde guerre mondiale. Il était déjà possible de leur faire réaliser des calculs complexes inaccessibles à la main. Ils sont alors capables de manipuler des informations  représentées sous une forme numérique. Grâce à la numérisation de textes, d'images,  de sons etc, les ordinateurs sont devenus des machines de traitement automatique de l'information. En français, le mot ordinateur s'est imposé en 1956.

Les premières machines sont réalisées avec des composants rudimentaires comme des relais électriques et des lampes à vide. Ceux-ci seront par la suite remplacés par des transistors. Elles sont très volumineuses et lourdes, consomment énormément d'énergie.

Mais surtout, leur utilisation est complexe car il est nécessaire d'écrire les programmes qu'elles exécutent  dans un langage très technique propre à chacune d'elles : un langage machine. De ce fait, leur diffusion et leur commercialisation sont très limitées. Deux inventions majeures vont lever ces difficultés :  les langages informatiques et la miniaturisation. C'est à la fin des années 50 que les premiers langages informatiques de programmation apparaissent. Ce sont des langages artificiels, c'est-à-dire inventés par l'homme, facilement lisibles et intelligibles.

Un programme spécifique appelé /compilateur/ ou /interprète/ se charge de traduire un texte écrit dans ce langage de programmation en langage machine. Les conséquences sont importantes : la programmation devient accessible à un plus grand nombre d'individus, et l'écriture d'un programme n'est plus spécifique à une machine. C'est le début du métier de programmeur.

Le changement d'ordinateur pour une autre version plus rapide ou plus puissante est facilité et moins coûteux car les programmes ne doivent pas être réécrits.

La deuxième évolution majeure, la miniaturisation, se déroule au début des années 70. Elle est réalisée par l'intégration des transistors et de tous les composants électroniques réalisant les calculs dans un ordinateur, dans un seul petit boîtier appelé microprocesseur. C'est Intel, entreprise fondée entre autres par Gordon Moore qui réalise cette performance technologique. Aujourd'hui des boîtiers de quelques millimètres peuvent contenir plusieurs milliards de transistors. La miniaturisation permet l'augmentation des performances et la baisse de la consommation d'énergie.

Gordon Moore est également connu pour avoir énoncé une prédiction sur ce processus de miniaturisation. /Le nombre de transistors intégrés dans les  microprocesseurs doublera tous les 2 ans/. Cette affirmation connue sous /la loi de Moore/ se vérifie depuis plus de 40 ans. On l'interprète dans le grand public comme /la puissance des ordinateurs double tous les 2 ans/.

Ce qui signifie en pratique que lorsque vous achetez un ordinateur, moins de 2 ans après vous pouvez trouver un autre modèle 2 fois plus puissant au même prix.

* Naissance d'Internet
  :PROPERTIES:
  :video:    https://player.vimeo.com/video/122104260
  :END:
Dans les années soixante, il existait aux États-Unis de gros centres de calcul abritant de très gros ordinateurs. Ceux-ci étaient reliés entre eux par des câbles qui leur permettaient de transporter l'information numérique : des réseaux informatiques (network en anglais souvent abrégé en net).

En période de guerre froide, les US avaient peur de voir leurs centres bombardés ou une ligne qui reliait 2 centres coupée. Il fallait pouvoir communiquer entre des centres stratégiques et pouvoir bénéficier à distance des résultats des supercalculateurs même en cas d'attaque nucléaire. Ils ont demandé aux chercheurs de proposer un système qui serait tolérant aux pannes… ou aux bombes.

L'idée a été de multiplier les centres et d'interconnecter les réseaux de chaque centre. Pour protéger l'ensemble,  la proposition a été de multiplier les chemins entre centres. Ainsi si un centre explosait ou qu'une ligne était coupée, les autres centres pourraient encore communiquer entre eux en passant par d'autres chemins : ce fut la naissance d'ARPANET (1971).

Ce système a tout de suite rencontré un grand succès. Il a ensuite évolué vers INTERNET, nom qu'on lui a donné au début des années 80 pour signifier qu'il s'agit d'une interconnexion de réseaux.

Selon le vieil adage /tous les chemins mènent à Rome/, le système de communication permet d'échanger des données entre 2 points en passant par n'importe quel chemin à l'intérieur d'internet.
* Comment ça marche?
  :PROPERTIES:
  :video:    https://player.vimeo.com/video/122104315
  :END:
Regardons un peu plus précisément comment fonctionne internet. Trois ingrédients importants interviennent dans le système ; le premier est l'adresse =IP= qui permet de fournir un nom et une adresse à chaque machine.
Chaque ordinateur connecté à internet a un numéro unique (un peu comme un numéro de téléphone, mais bien plus long !). Ce numéro dépend de l'endroit où l'ordinateur se trouve dans internet et permet donc de trouver un chemin dans l'interconnexion de réseaux. On appelle ce numéro l'adresse =IP=. De façon très simplifiée, l'adresse =IP= comporte une partie identifiant un réseau dans cette interconnexion et une autre partie identifiant la machine au sein de ce réseau.

Pour échanger des informations d'un ordinateur vers un autre, celui qui /envoie/ l'information doit donc connaître l'adresse =IP= du destinataire, et pour obtenir une réponse, l'émetteur doit impérativement fournir dans chaque message envoyé sa propre adresse =IP=. Tous les messages échangés sur Internet sont donc de la forme :
=n°=IP= destinataire / information / n°=IP= émetteur=.

Le deuxième ingrédient concerne le /Routage/ des messages sur le réseau.
Si les ordinateurs émetteur et destinataire sont dans le même réseau, le principe est simple : l'ordinateur émetteur envoie son message sur ce réseau et chaque ordinateur du réseau le lit. Les destinataires peuvent alors s'intéresser aux messages qui leurs sont destinés.
Si le destinataire n'est pas dans le même réseau, la transmission ne peut plus se faire directement à l'ordinateur du destinataire. L'émetteur envoie le message à une machine connectée à la fois à ce réseau et à un ou plusieurs autres réseaux. Cette machine est une passerelle/routeur qui réalise effectivement l'interconnexion. Le routeur renvoie alors le message vers les autres réseaux pour poursuivre son chemin. Et ce processus se répète jusqu'à ce que le message arrive à destination.


Enfin le troisième ingrédient concerne le nommage des machines.
En effet, ce sont des femmes et des hommes qui utilisent ces machines. Pour désigner un destinataire, personne ne manipule directement des adresses =IP= qui sont des numéros bien plus longs que les numéros de téléphone. Dans notre interface avec le monde d'internet nous connaissons plutôt des noms comme =www.univ-lille3.fr= ou encore =www.service-public.fr=. Le lien entre adresses =IP= et noms se fait par le biais des /serveurs de noms/ qui, à la manière d'une liste de contacts dans notre téléphone, stockent un ensemble de nom et d'adresses =IP=.

Très concrètement, regardons par exemple ce qui se passe lorsque je veux consulter la page d'accueil de Lille 3.
tout d'abord, je clique sur un lien vers le site de l'université. Ce lien contient le nom de la machine capable de me fournir la page d'accueil : =www.univ-lille3.fr=. Mon ordinateur va donc contacter un serveur de noms pour connaître l'adresse =IP= de cette machine. Une fois que cette adresse =IP= est connue, il peut communiquer avec =www.univ-lille3.fr= et envoyer à cette machine un message qui demande le contenu de cette page d'accueil. Le message contient bien entendu l'adresse =IP= de mon ordinateur, ainsi la machine peut me répondre en renvoyant le contenu qui m'intéresse. Il ne reste plus alors à mon ordinateur qu'à afficher ce contenu.
* Que se passe-t-il quand on se connecte à Internet?
  :PROPERTIES:
  :video:    https://player.vimeo.com/video/122104376
  :END:
Examinons les conséquences de l'organisation d'Internet lorsqu'on veut s'y connecter ...

** Rejoindre un réseau local
L'ordinateur, le smartphone ou la tablette qui doit accéder à Internet doit d'abord rejoindre un réseau. Nous verrons un peu plus loin les différents moyens de se connecter à un réseau que ce soit par le wifi, un câble ou le réseau de téléphonie mobile.

** Obtenir les 3 informations nécessaires
De plus, nous avons vu que pour communiquer avec d'autres machines, notre ordinateur a besoin de trois informations importantes : le numéro =IP=, l'adresse du routeur qui relie ce réseau à Internet, et l'adresse du serveur de noms. Ces trois informations sont fournies à notre machine immédiatement après qu'elle ait rejoint le réseau. C'est une machine particulière dans le réseau local qui fournit ces informations et donc une autorité locale qui décide de ces attributions. Par exemple chez vous, c'est votre box ADSL sous votre responsabilité qui s'en charge. La box elle-même, qui est un ordinateur presque comme les autres, reçoit ces 3 informations de votre fournisseur d'accès à Internet (FAI) quand elle démarre. Avec la 4G c'est une machine chez votre opérateur mobile qui est sollicitée…

** Pas de garantie de confidentialité
Autre remarque importante, le principe d'internet repose sur un envoi de proche en proche des messages transmis entre émetteur et destinataire à travers les ordinateurs (routeurs) qui réalisent l'interconnexion. Dans ce mode de fonctionnement, il n'y a de garantie ni de la confidentialité ni de l'intégrité des messages. Chaque ordinateur participant à la transmission peut lire et modifier les données échangées. Si l'on veut transmettre des données sensibles, il faut donc mettre en œuvre des procédures spécifiques additionnelles pour assurer l'authenticité et/ou la confidentialité des données transmises. Par exemple,  pour transmettre des mots de passe ou des numéros de carte bleue, il est nécessaire de crypter les messages pour les rendre indéchiffrables par des curieux.

** Filtrage et suivi possible
Une autre conséquence du fonctionnement d'internet, est que des filtres peuvent être mis en place sur des routeurs pour empêcher certains messages d'être transmis. Ces filtres peuvent se limiter à contrôler les adresses des destinataires pour empêcher de contacter certaines machines. Ils ont par exemple été mis en œuvre dans des pays voulant s'isoler ou censurer quelques services comme twitter, ou encore wikileaks...  Les filtres peuvent également concerner les contenus des messages comme dans le cas des filtres parentaux sur les box ADSL (qui incluent une fonction de routeur). Les entreprises et organisations emploient aussi cette possibilité pour garder les traces des connexions et répondre ainsi à la contrainte légale de pouvoir retrouver les protagonistes d'un échange illicite.

** Impossibilité d'éviter la copie
La dernière remarque porte sur l'emploi trompeur du mot /envoi/. Lorsqu'une machine /envoie/ un message, elle réalise en réalité une copie du message sur le réseau. Libre alors à elle de supprimer ou conserver la version originelle du message. C'est une situation que l'on rencontre régulièrement dans le monde /numérique/ et qui rend difficile la lutte contre les copies illicites. Mais nous aurons l'occasion d'en reparler plus tard.

Mais finalement, pourquoi avoir conçu et suivi cette organisation complexe d'interconnexion de réseaux? En fait, un très grand réseau où toutes les machines seraient directement reliées est impossible à concevoir. Il faudrait multiplier les câbles et même dans une solution sans fil, à l'image d'une discussion à plusieurs personnes, au delà d'une certaine limite les discussions des uns couvrent inévitablement celle des autres à tel point qu'on ne peut plus discuter! Les réseaux locaux avec des discussions locales ne peuvent donc fonctionner que jusqu'à une certaine taille au delà de laquelle une structuration par interconnexion devient obligatoire.

* Les supports physiques de transmission de l'information
  :PROPERTIES:
  :video:    https://player.vimeo.com/video/122104443
  :END:

Internet et plus généralement les réseaux informatiques peuvent utiliser plusieurs types de supports pour transporter l'information numérique. On  distinguera les supports physiques, les câbles qui peuvent être électriques ou optiques et les ondes électromagnétiques comme le Wifi, le bluetooth ou les réseaux de téléphonie mobiles. Nous allons voir qu'une connaissance minimale de ces technologies va nous permettre de mieux comprendre les enjeux qu'ils cachent.

** Le débit
Tout d'abord nous devons introduire la notion de débit. Si on prend l'image d'un robinet d'eau, on voit bien qu'un robinet avec un gros tuyau me permettra de remplir mon seau beaucoup plus vite qu'avec un petit robinet qui ne laisse passer qu'un léger filet d'eau. Le débit dans ce cas est une quantité d'eau par seconde.
La problématique est la même pour le réseau Internet. Nous avons vu précédemment que les informations numériques étaient ramenées à des suites de bits (des 0 et des1). Le débit sera donc pour les réseaux en nombre de bits par seconde. Comme cette information circule très vite on parlera en fait de milliers de bits par seconde (kb/s), de millions de bits par seconde (Mb/s) voire de milliards de bits par seconde (Gb/s).
À titre indicatif, voici quelques ordres de grandeur, un document texte d'une dizaine de pages se code avec quelques kbits, un fichier mp3 de musique de quelques minutes se compte en Mbits alors qu'un film d'une heure correspond à plusieurs Gbits.

** Les supports et les normes relatives à leur utilisation
Nous allons dans la suite présenter les différents supports utilisés dans les réseaux. Ils ont connu de fortes évolutions depuis les débuts d'internet. Parfois cette évolution est purement matérielle comme l'apparition de la fibre optique, d'autres fois l'évolution consiste en une meilleure utilisation du support. L'utilisation du support est décrite dans un ensemble de normes comme par exemple la 3G ou la 4G qui tous deux utilisent le support des ondes. Aussi la présentation suivante s'appuie à la fois sur les deux notions de norme et de support.

** Les câbles
S'agissant des câbles on distingue les câbles électriques et les fibres optiques qui transportent la lumière. Ces dernières sont évidemment beaucoup plus rapides et sont utilisées prioritairement quand c'est possible. C'est le cas par exemple de la plupart des câbles sous-marins qui traversent les océans pour relier les continents, certains ont des débits supérieurs à 100Gb/s.
Des câbles électriques spécifiques pour les réseaux informatiques peuvent également être très rapides mais sur des courtes distances.
C'est en général la solution retenue pour connecter les ordinateurs d'un réseau local dans les entreprises. C'est aussi le cas pour les ordinateurs à votre disposition dans les salles informatiques de l'université.

En revanche, ce n'est pas le cas de la plupart du réseau français qui relie la majorité des foyers du pays. Les lignes qu'on appelle ADSL, sont en fait les câbles de l'ancien réseau téléphonique qui a été construit à l'origine pour transporter la voix du téléphone et non des informations numériques à très grande vitesse. Cela explique que les connexions dont nous disposons à domicile sont de qualité moyenne et ne permettent pas le très haut débit, sauf à passer par une fibre optique, c'est ce que proposent désormais beaucoup de fournisseurs d'accès dans certains quartiers.

Évidemment, le câblage de toutes les zones habitées avec de la fibre optique représente un enjeu social et économique considérable. Alors que les lignes de téléphone sont présentes sur l'ensemble du territoire, seules les grandes agglomérations sont couvertes par l'équipement en fibres optiques. Cela représente un grand facteur d'inégalité...

** Les ondes
Depuis le XIXème siècle, les hommes ont réussi à s'échanger des informations via les ondes électromagnétiques. La radio puis la télévision ont copieusement utilisé ce principe qui utilise un système d'antennes émettrices et réceptrices. Nous savons transporter de la même façon des informations numériques. À chaque réseau son antenne, certains appareils sont équipés d'une antenne Wifi, d'une antenne Bluetooth et pour les téléphones d'une antenne de réseau de données mobiles.
Ces différentes technologies sont essentiellement utilisées pour nos connexions nomades, c'est-à-dire avec des appareils mobiles tels que des ordinateurs portables, des tablettes ou des smartphones. Fondamentalement, elles permettent toutes la même chose, c'est à dire un accès complet à Internet.

 
** Les connexions nomades
  :PROPERTIES:
  :video:    https://player.vimeo.com/video/122104499
  :END:
On se retrouve régulièrement à devoir choisir parmi plusieurs moyens pour se connecter à internet avec nos appareils nomades. Les arguments qui entrent dans ce choix sont très variés. On pense bien entendu au coût. Par exemple, l'utilisation du wifi de l'université est gratuite. Les accès internet par le biais d'une box sont généralement inclus dans un forfait illimité, en revanche le coût de l'utilisation d'internet à l'aide de connexions 2G/3G/4G peut rapidement exploser.

Un autre élément déterminant est la disponibilité de la connexion. En effet, selon les endroits où l'on se trouve, le réseau mobile peut être indisponible ou de très faible qualité, inversement il n'y a pas toujours un accès Wifi à notre portée. Notons que si l'on se déplace de plus de quelques mètres, il devient quasi-impossible de rester connecté à un réseau wifi qui a une portée assez faible. Les réseaux de téléphonie mobiles autorisent par contre une connexion permanente sur des longues distances à pied ou en voiture par exemple.

Depuis les années 90, le réseau de téléphonie mobile permet le transfert de données numériques.

Mais les normes et les techniques évoluent et sont de plus en plus rapides. Les premières générations proposaient des débits très faibles qui ne permettaient pas par exemple le transfert d'images ou de musique dans des temps raisonnables. Nous en sommes à la quatrième génération de la technologie, la 4G offre maintenant des débits qui dépassent parfois ceux des connexions wifi.

** La rapidité du réseau
Toutefois, la qualité du lien qui relie votre appareil électronique au réseau n'est pas le seul responsable du débit. Réfléchissons à ce qui fait que ma liaison est lente ou rapide. Tout d'abord il faut se rappeler que les débits indiqués par les constructeurs ou les opérateurs sont toujours théoriques et correspondent au maximum possible dans les meilleures conditions. En pratique, ces conditions sont rarement réunies et les débits peuvent être considérablement ralentis en fonction de plusieurs facteurs :

- le premier facteur que l'on peut citer est l'éloignement, celui-ci joue aussi bien pour les connexions par onde que pour les connexions par câble. Par exemple, les accès ADSL sont très différents selon qu'on a la chance d'habiter près d'un noeud de raccordement aux abonnés (qui contient les machines des fournisseurs d'accès) ou si on en est plus éloigné, les débits peuvent alors être 10 ou 20 fois plus rapides, … pour le même prix d'abonnement.
- De même, si on s'éloigne au fond du jardin avec son portable, la connexion wifi à notre box va considérablement perdre en qualité, jusqu'à ne plus être accessible.
- un autre facteur important est le nombre d'utilisateurs du réseau, quelle que soit la technologie utilisée, on peut voir les autoroutes de l'information comme de vraies autoroutes, lorsqu'il y a beaucoup de voitures le trafic est ralenti, de la même façon, si une connexion wifi par exemple est partagée par plusieurs utilisateurs, le débit sera reparti entre eux et aucun d'entre eux n'aura accès au débit maximum
- l'encombrement du réseau est encore un autre facteur, les routeurs peuvent être vus comme les péages des autoroutes, ce sont des goulots d'étranglement qui bouchonnent lorsque beaucoup de demandes arrivent en même temps
- enfin, il arrive que l'actualité fasse que certains sites soient sollicités au même moment par des milliers ou des millions d'utilisateurs, le site ne pouvant répondre à tout le monde en même temps, le temps de réponse pour chacun se trouve considérablement ralentie.

Ainsi, il est très fréquent de constater que la vitesse de transmission des données varie dans le temps ; varie selon les endroits ou les moyens avec lesquels on se connecte à Internet ou encore varie selon les sites que l'on visite ou les services que l'on demande. Comme nous venons de le voir, la vitesse d'une connexion dépend de nombreux facteurs. Difficile donc de savoir d'où vient un ralentissement quand il intervient. Mais parfois, le simple changement du mode de connexion utilisé peut faire des miracles. Soyez agiles !!!

* Société : qui décide sur Internet?
  :PROPERTIES:
  :video:    https://player.vimeo.com/video/122104174
  :END:
** Les normes et instituts de normes
Pouvons-nous communiquer si nous ne comprenons pas la même langue? Non, sauf bien sûr si nous avons la chance d'avoir un interprète et dans ce dernier cas la communication n'est pas aussi simple. La même situation se retrouve dans les réseaux informatiques.

Pour faciliter les communications entre les machines, des normes ont été établies. L'avantage de la norme si elle est bien documentée, publique et libre d'accès est que chacun, constructeur ou éditeur de logiciel, peut la réaliser dans ses produits.

C'est le rôle des instituts de normes, comme l'ISO qui regroupe la plupart des pays du monde, et de l'AFNOR en France, d'éditer et diffuser ces normes.

De très nombreuses normes entrent en jeu dans le fonctionnement d'Internet et des réseaux informatiques. C'est le cas de du protocole de l'internet dans lequel on retrouve la définition des adresses =IP= dont nous avons parlé. C'est aussi le cas des protocoles et langages du Web dont nous parlerons bientôt. L'existence de ces normes est une raison majeure du succès planétaire du web. Sans elles, le web serait sans doute un archipel d'îles isolées plutôt qu'une toile.

** Pressions
Mais imaginez maintenant un standard industriel breveté et protégé par une unique société à la place d'une norme mondiale libre et ouverte. Cette société aurait un pouvoir considérable. Évidemment, les enjeux économiques du numérique étant si importants que de nombreuses tentations ont été observées pour contourner les normes ou imposer son standard. C'est un peu le rôle de chacun de veiller à éviter ces dérives et une éducation numérique contribue à donner des armes aux citoyens pour comprendre ces enjeux et agir en conséquence.

À voir "Une contre-histoire d'internet", de Sylvain Bergère. Retour sur les mouvements de défense des libertés sur internet, apparus en réaction à la régulation croissante du web : https://www.youtube.com/watch?v=tztUb=IP=b5oQ&feature=youtu.be

** Les structures politiques
Au niveau d'internet, en plus des normes qui régissent les moyens de communiquer les informations à travers le réseau, il faut également contrôler l'organisation du réseau. Nous pouvons illustrer cela en étudiant la structure politique mise en œuvre pour attribuer les adresses =IP= et les noms.

Nous avons expliqué que lorsqu'une machine rejoint internet, elle rejoint d'abord un réseau local et l'autorité possédant ce réseau local lui attribue un numéro =IP=. Ce numéro est choisi dans un ensemble de numéros dont un organisme de tutelle a confié la responsabilité. Cet organisme de tutelle a lui-même un ensemble de numéros à sa disposition et ainsi de suite. Au sommet de cette hiérarchie de responsabilités, se trouve l'ICANN. L'ICANN délègue ensuite à 5 structures correspondant à 5 grandes régions du monde. Ceux-ci délèguent aux organisations locales dans lesquelles on retrouve en autres les sociétés qui vous louent les BOX ADSL. Il y en a plusieurs centaines en France.

Pour les noms de l'internet l'organisation politique est très similaire, hiérarchique également avec au sommet encore une fois l'ICANN. On retrouve cette hiérarchie dans la façon avec laquelle sont construit les noms. Par exemple la machine appelée =www.univ-lille3.fr= désigne une machine appelée =www= dans un domaine de nommage plus grand, =univ-lille3.fr=, qui comprend également =live3.univ-lille3.fr= ou =formations.univ-lille3.fr= ... Le domaine =univ-lille3.fr= est lui même dans un domaine plus grand encore le =.fr=.

L'université gère les noms dans son domaine alors que l'AFNIC gère tous les noms en =.fr=.

** À qui appartient internet ?
La structure politique que nous venons de décrire a son miroir technologique. En effet, l'ensemble machines qui assurent le service d'associer noms et adresses forme également une hiérarchie. Comme nous l'avons vu dans une activité précédente, au sommet de cette hiérarchie se trouvent seulement 13 machines. Si elles s'arrêtaient, internet serait inutilisable. Des cyberattaques ont même eu lieu plusieurs fois pour tenter de les mettre en panne... Ces 13 ordinateurs sont presque tous aux États-Unis et appartiennent souvent à des sociétés privées. On est en droit de se demander une fois de plus à qui donc appartient internet ?

L'organisation politique des noms et des =IP= est elle aussi souvent remise en cause car les institutions importantes comme l'ICANN sont de droit américain.

La plupart des câbles qui sillonnent la planète appartiennent également à des sociétés privées. Aux États-Unis, Comcast, le plus gros opérateur est en passe de racheter le second (Time Warner Cable).

Et les routeurs dont nous avons parlé sont très souvent fabriqués par l'entreprise Cisco, une entreprise américaine....

À tout niveau, des situations de monopole peuvent apparaître et avec elles, le risque de perdre des libertés pour l'usager : liberté de choix, liberté de communiquer.

** Une société de surveillance généralisée
Nous avons vu que les informations que nous communiquons passent par des routeurs. Ceux-ci peuvent assurer des fonctions de filtrage des contenus et de journalisation (ou mémorisation de l'historique des échanges). En France, les fournisseurs d'accès à internet, dont l'université, sont tenus de pouvoir répondre à des enquêtes provenant de juges : qui a consulté ce site tel jour à telle heure ? Donc, à l'université, au travail ou chez vous, une mémorisation est faite.

Toutefois mémorisation ne signifie pas systématiquement surveillance ou espionnage. La CNIL par exemple, et bien sûr la justice, doivent protéger les citoyens contre ces abus. Mais leurs moyens ne sont pas toujours à la hauteur de leurs missions... Et les affaires comme PRISM ont montré que cette question dépasse largement le cadre Français.
